In [2]:
import pandas as pd
import numpy as np
import platform
import matplotlib
import seaborn as sns
from matplotlib import font_manager, rc
from matplotlib import ticker

import statsmodels.formula.api as smf # 통계 모형
import statsmodels.api as sm
import matplotlib.pyplot as plt

import scipy as sp
from scipy.stats import probplot
from sympy import Symbol, solve

sns.set()
%precision 3
# 소수점 3자리까지 표현

%matplotlib inline
#그래프를 주피터 노트북에 그리기


# Window
if platform.system() == 'Windows':
    matplotlib.rc('font', family='Malgun Gothic')
elif platform.system() == 'Darwin': # Mac
    matplotlib.rc('font', family='AppleGothic')
else: #linux
    matplotlib.rc('font', family='NanumGothic')

# 그래프에 마이너스 표시가 되도록 변경
matplotlib.rcParams['axes.unicode_minus'] = False

# 한글 폰트 설정
font_location = 'C:/Windows/Fonts/MALGUNSL.TTF' #맑은고딕
font_name = font_manager.FontProperties(fname=font_location).get_name()
rc('font',family=font_name)

In [3]:
class Ex_class:
    def __init__(self, data1 , data2):
        self.r = data1
        self.l = data2

x = Ex_class(3 , 4)
x.r + x.l

7

In [4]:
class Rectangle: #붕어빵 틀
    count = 0 # 클래스 변수

    #초기자(iniializer)
    def __init__(self , width, height): #붕어빵 석쇠
        #self.* : 인스턴스 변수
        self.width = width
        self.height = height
        Rectangle.count += 1

    # 메서드

    def calcArea(self):
        area = self.width * self.height
        return area

r = Rectangle(2,3) #인스턴스 생성 ==> self = r , width = 2 , height = 3

area = r.calcArea() #메서드 호출 ==> self = r , r.width = 2 , r.height = 3 ==> area = r.width * r.height ==> area = 6
print("area :" , area)

r.width = 10 #인스턴스 변수 액세스
print("width :" , r.width)

print(Rectangle.count) #클래스 변수 액세스
print(r.count)

area : 6
width : 10
1
1


In [5]:
class Animal :
    def __init__(self , name):
        self.name = name
    def move(self):
        print('move')
    def speak(self):
        pass

class Dog(Animal): #파싱 클래스
    def speak(self):
        print('bark')
class Duck (Animal):
    def speak(self):
        print('quack')


dog = Dog('doggy') #부모 클래스 생성자 ==> self = dog ==> dog.name = doggy , dog.name ==> print(move)
n = dog.name #부모클래스의 인스턴스 변수
dog.move() #부모클래스의 매서드
dog.speak() #파싱클래스의 맴버


animals = [Dog('doggy') , Duck('duck')]

for a in animals:
    a.speak()

move
bark
bark
quack


In [6]:
A = '96 80 76 96 88 75 78 89 92 70'
B = '67 83 96 90 85 75 82 89 92 75'

A = list(map(int , A.split(' ')))
B = list(map(int , B.split(' ')))

k_score1 = np.array([A])
k_score2 = np.array([B])

score = np.append(k_score1 , k_score2)
score


array([96, 80, 76, 96, 88, 75, 78, 89, 92, 70, 67, 83, 96, 90, 85, 75, 82,
       89, 92, 75])

In [7]:
sc = np.hstack([k_score1, k_score2])
print(sc)

[[96 80 76 96 88 75 78 89 92 70 67 83 96 90 85 75 82 89 92 75]]


In [8]:
df = pd.DataFrame({'name' : ['KIM' , 'LEE' , 'Park' , 'Bae' , 'Kang'] , 'age' : [24 , 32 , 43 , 24 , np.nan] , 'height' : [160 , 170 ,165 , 173 ,158]})
df

name   age  height
0   KIM  24.0     160
1   LEE  32.0     170
2  Park  43.0     165
3   Bae  24.0     173
4  Kang   NaN     158

In [9]:
df['rank_average'] = df['age'].rank(method = 'min' , ascending = False , na_option = 'bottom')
df

name   age  height  rank_average
0   KIM  24.0     160           3.0
1   LEE  32.0     170           2.0
2  Park  43.0     165           1.0
3   Bae  24.0     173           3.0
4  Kang   NaN     158           5.0

In [10]:
dfObj = df.sort_values(by = ['name' , 'age'])
dfObj

name   age  height  rank_average
3   Bae  24.0     173           3.0
0   KIM  24.0     160           3.0
4  Kang   NaN     158           5.0
1   LEE  32.0     170           2.0
2  Park  43.0     165           1.0

## 벡터 기본 연산

In [11]:
x = np.array([1,2,3,4,5])
y = np.array([-1,-2,-3,-4,-5])

print(x+y)

print(np.matmul(x , y.T))

print(np.outer(x, y.T))

print(np.multiply(x, y.T))

print(np.hstack([x, y.T]))

[0 0 0 0 0]
-55
[[ -1  -2  -3  -4  -5]
 [ -2  -4  -6  -8 -10]
 [ -3  -6  -9 -12 -15]
 [ -4  -8 -12 -16 -20]
 [ -5 -10 -15 -20 -25]]
[ -1  -4  -9 -16 -25]
[ 1  2  3  4  5 -1 -2 -3 -4 -5]


In [12]:
print(np.diag([1 for _ in range(5)]))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [13]:
b = np.arange(12).reshape(4,3)
df = pd.DataFrame(b , columns = ['X1' , 'X2' , 'X3'])
df

X1  X2  X3
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11

In [14]:
df.loc[1 , ['X1' , 'X3']] = np.nan
df.loc[2, 'X2'] = np.nan
df.loc[3 , 'X2'] = np.nan
df

X1   X2    X3
0  0.0  1.0   2.0
1  NaN  4.0   NaN
2  6.0  NaN   8.0
3  9.0  NaN  11.0

In [15]:
df_f = df.fillna(method = 'ffill' , limit = 1)
df_f

X1   X2    X3
0  0.0  1.0   2.0
1  0.0  4.0   2.0
2  6.0  4.0   8.0
3  9.0  NaN  11.0

In [16]:
df_b = df.fillna(method = 'bfill')
df_b

X1   X2    X3
0  0.0  1.0   2.0
1  6.0  4.0   8.0
2  6.0  NaN   8.0
3  9.0  NaN  11.0

In [17]:
df_xlm = df.fillna(df.mean()['X1'])
df_xlm

X1   X2    X3
0  0.0  1.0   2.0
1  5.0  4.0   5.0
2  6.0  5.0   8.0
3  9.0  5.0  11.0

In [18]:
df_xlm_to_x2 = df.fillna(df.mean() ['X1' : 'X2'])
df_xlm_to_x2

X1   X2    X3
0  0.0  1.0   2.0
1  5.0  4.0   NaN
2  6.0  2.5   8.0
3  9.0  2.5  11.0

In [20]:
x = np.array([1,2,3,4,5])
sample_df = pd.DataFrame({
    'col1' : x,
    'col2' : x+2,
    'col3' : ["a" , "b" , "c" , "d" , "e"]
})

sample_df

col1  col2 col3
0     1     3    a
1     2     4    b
2     3     5    c
3     4     6    d
4     5     7    e

In [21]:
sample_df.drop('col3' , axis = 1)

col1  col2
0     1     3
1     2     4
2     3     5
3     4     6
4     5     7

In [23]:
sample_df.query('index == 0')

col1  col2 col3
0     1     3    a

In [25]:
sample_df.query('col3 == "b"')

col1  col2 col3
1     2     4    b